// js/products.js · fuente única de verdad del catálogo.
// Datos extraídos de los catálogos oficiales de Armadera (2021 y 2023).
// Campos: slug, nombre, precio (CLP entero; 0 + consultar:true = "Consultar precio"),
// edad, descripcion, incluye[], favorece[], materiales, medidas (opcional),
// imagenes[] (la 1ª es la principal; el resto arman la galería),
// destacado, stock, consultar (opcional).
export const products = [
  {
    slug: 'pajaros-armo-pajaras-pinto', nombre: 'Pájaros Armo, Pájaras Pinto', precio: 35000,
    edad: 'Desde 3 años',
    descripcion: 'Set de juego de ensamble con 6 aves chilenas de madera para armar y pintar. Cada ave viene con su guía explicativa para conocer nuestra fauna mientras se crea.',
    incluye: ['6 aves chilenas de madera', 'Guía completa y explicativa de cada ave', 'Témperas', 'Pincel', 'Mezclador / paleta'],
    favorece: ['Motricidad fina', 'Coordinación viso-motriz', 'Trabajo bi-manual', 'Inicio del lenguaje e imitación', 'Concentración y cultura'],
    materiales: 'Terciado, terminaciones con aceites naturales',
    imagenes: ['/img/productos/pajaros-armo-pajaras-pinto/1.jpg', '/img/productos/pajaros-armo-pajaras-pinto/2.jpg', '/img/productos/pajaros-armo-pajaras-pinto/3.jpg', '/img/productos/pajaros-armo-pajaras-pinto/4.jpg', '/img/productos/pajaros-armo-pajaras-pinto/5.jpg', '/img/productos/pajaros-armo-pajaras-pinto/6.jpg'],
    destacado: true, stock: true,
  },
  {
    slug: 'animales-campo-chileno', nombre: 'Animales del Campo Chileno', precio: 35000,
    edad: 'Desde 6 meses',
    descripcion: 'Set de 14 figuras de madera con forma de animales del campo para jugar libremente. Incluye un póster ilustrado donde cada animal cuenta una característica propia.',
    incluye: ['14 figuras de madera con forma de animales', 'Póster ilustrado con una característica de cada animal'],
    favorece: ['Acción y reacción', 'Motricidad fina', 'Coordinación viso-motriz', 'Inicio del lenguaje e imitación', 'Juego pre simbólico y simbólico'],
    materiales: 'Pino, terminaciones con aceites naturales',
    imagenes: ['/img/productos/animales-campo-chileno/1.jpg', '/img/productos/animales-campo-chileno/2.jpg', '/img/productos/animales-campo-chileno/3.jpg', '/img/productos/animales-campo-chileno/4.jpg', '/img/productos/animales-campo-chileno/5.jpg'],
    destacado: false, stock: true,
  },
  {
    slug: 'suena-con-el-bosque-ideal', nombre: 'Sueña con el Bosque Ideal', precio: 35000,
    edad: 'Desde 3 años',
    descripcion: 'Set con 11 timbres de animales del bosque chileno producidos en madera. Los niños timbran, conocen cada especie y luego pintan su propio bosque.',
    incluye: ['11 timbres de animales del bosque chileno', 'Guía con información de cada animal', '3 láminas para timbrar y pintar', 'Lápices', 'Tinta para timbres'],
    favorece: ['Motricidad fina', 'Coordinación viso-motriz', 'Trabajo bi-manual', 'Inicio del lenguaje e imitación', 'Conexión con la naturaleza'],
    materiales: 'Madera, terminaciones con aceites naturales',
    imagenes: ['/img/productos/suena-con-el-bosque-ideal/1.jpg', '/img/productos/suena-con-el-bosque-ideal/2.jpg', '/img/productos/suena-con-el-bosque-ideal/3.jpg', '/img/productos/suena-con-el-bosque-ideal/4.jpg', '/img/productos/suena-con-el-bosque-ideal/5.jpg', '/img/productos/suena-con-el-bosque-ideal/6.jpg'],
    destacado: true, stock: true,
  },
  {
    slug: 'acrobatas', nombre: 'Acróbatas', precio: 35000,
    edad: 'Desde 12 meses',
    descripcion: 'Juego de equilibrio con figuras de acróbatas que se apilan y balancean de mil formas. Desafía la creatividad y la motricidad mientras se arman torres y pirámides.',
    incluye: ['9 figuras de acróbatas', 'Stickers para personalizarlos', 'Guía "¿Cómo equilibrar a tus acróbatas?"'],
    favorece: ['Inicio del lenguaje e imitación', 'Motricidad fina', 'Imaginación', 'Coordinación', 'Equilibrio'],
    materiales: 'Pino, terminaciones con aceites naturales',
    imagenes: ['/img/productos/acrobatas/1.jpg', '/img/productos/acrobatas/2.jpg', '/img/productos/acrobatas/3.jpg', '/img/productos/acrobatas/4.jpg', '/img/productos/acrobatas/5.jpg'],
    destacado: true, stock: true,
  },
  {
    slug: 'multiforma', nombre: 'Multiforma', precio: 160000,
    edad: 'Desde 12 meses',
    descripcion: 'Estructura de aventura para trepar, deslizarse y equilibrarse. Se compone de tres partes (triángulo, semicírculo y rampla) que se combinan de distintas formas.',
    incluye: ['Triángulo', 'Semicírculo', 'Rampla'],
    favorece: ['Motricidad gruesa', 'Equilibrio', 'Coordinación', 'Estabilidad'],
    materiales: 'Madera (pino y terciado). Soporta hasta 40 kg',
    imagenes: ['/img/productos/multiforma/1.jpg', '/img/productos/multiforma/2.jpg', '/img/productos/multiforma/3.jpg', '/img/productos/multiforma/4.jpg'],
    destacado: false, stock: true,
  },
  {
    slug: 'equilibrio', nombre: 'Equilibrio', precio: 60000,
    edad: 'Desde 12 meses',
    descripcion: 'Camino de equilibrio conformado por 3 piezas de un metro y 4 bases que se ordenan a gusto para crear distintos recorridos.',
    incluye: ['3 piezas de un metro cada una', '4 bases'],
    favorece: ['Motricidad gruesa', 'Equilibrio', 'Coordinación', 'Estabilidad', 'Sistema neuromuscular'],
    materiales: 'Pino. Soporta hasta 40 kg',
    imagenes: ['/img/productos/equilibrio/1.jpg', '/img/productos/equilibrio/2.jpg', '/img/productos/equilibrio/3.jpg', '/img/productos/equilibrio/4.jpg'],
    destacado: false, stock: true,
  },
  {
    slug: 'tipi', nombre: 'Tipi', precio: 70000,
    edad: 'Desde 10 meses',
    descripcion: 'Un versátil refugio de fácil armado para esconderse, gatear y jugar. Incluye pintura de pizarra en una de sus paredes para dibujar con tiza.',
    incluye: ['Estructura tipo tipi de fácil armado', 'Una pared con pintura de pizarra'],
    favorece: ['Acción y reacción', 'Gateo', 'Marcha', 'Juego simbólico'],
    materiales: 'Terciado, terminaciones con aceites naturales',
    medidas: '94 cm de alto × 30 cm de ancho · base 76 × 76 cm',
    imagenes: ['/img/productos/tipi/1.jpg', '/img/productos/tipi/2.jpg', '/img/productos/tipi/3.jpg', '/img/productos/tipi/4.jpg', '/img/productos/tipi/5.jpg'],
    destacado: false, stock: true,
  },
  {
    slug: 'semicirculo', nombre: 'Semicírculo', precio: 70000,
    edad: 'Desde 12 meses',
    descripcion: 'Arco de forma semi curva ideal para trepar, balancearse y explorar el movimiento. Parte de la línea de estructuras de Armadera.',
    incluye: ['Estructura en forma de semicírculo'],
    favorece: ['Equilibrio', 'Coordinación', 'Motricidad gruesa', 'Estabilidad'],
    materiales: 'Terciado y pino, terminaciones con aceites naturales. Soporta hasta 40 kg',
    medidas: '54 cm de ancho × 94 cm de largo',
    imagenes: ['/img/productos/semicirculo/1.jpg', '/img/productos/semicirculo/2.jpg', '/img/productos/semicirculo/3.jpg'],
    destacado: false, stock: true,
  },
  {
    slug: 'muro-de-escalada-180', nombre: 'Muro de escalada 1.80 × 1.06 m', precio: 270000,
    edad: 'Todas las edades',
    descripcion: 'Muro de escalada de 1.80 × 1.06 metros para el desarrollo de la motricidad, la fuerza y la confianza. Pensado para espacios interiores y exteriores.',
    incluye: ['Muro de escalada con presas de madera'],
    favorece: ['Motricidad gruesa', 'Fuerza', 'Coordinación', 'Confianza'],
    materiales: 'Madera, terminaciones con aceites naturales',
    medidas: '1.80 × 1.06 metros',
    imagenes: ['/img/productos/muro-de-escalada-180.jpg'],
    destacado: true, stock: true,
  },
  {
    slug: 'muro-de-escalada-220', nombre: 'Muro de escalada 2.20 × 1.40 m', precio: 360000,
    edad: 'Todas las edades',
    descripcion: 'Versión grande del muro de escalada, de 2.20 × 1.40 metros, para el desarrollo de la motricidad, la fuerza y la confianza en niñas y niños.',
    incluye: ['Muro de escalada con presas de madera'],
    favorece: ['Motricidad gruesa', 'Fuerza', 'Coordinación', 'Confianza'],
    materiales: 'Madera, terminaciones con aceites naturales',
    medidas: '2.20 × 1.40 metros',
    imagenes: ['/img/productos/muro-de-escalada-220.jpg'],
    destacado: false, stock: true,
  },
  {
    slug: 'triangulo', nombre: 'Triángulo', precio: 80000,
    edad: 'Desde 12 meses',
    descripcion: 'Estructura triangular para trepar, ideal para espacios interiores y exteriores. Diseñada para escaladores y escaladoras en formación.',
    incluye: ['Estructura triangular (no plegable)'],
    favorece: ['Equilibrio', 'Coordinación', 'Motricidad gruesa', 'Fuerza'],
    materiales: 'Terciado y pino, aceites naturales y tinte verde. Soporta hasta 40 kg',
    medidas: '90 cm de alto × 68 cm de ancho',
    imagenes: ['/img/productos/triangulo/1.jpg', '/img/productos/triangulo/2.jpg'],
    destacado: false, stock: true,
  },
  {
    slug: 'rampla', nombre: 'Rampla', precio: 60000,
    edad: 'Desde 12 meses',
    descripcion: 'Rampla reversible que se usa por ambos lados: como resbalín o como muro de escalada. Perfecta para combinar con el triángulo o el semicírculo.',
    incluye: ['Rampla reversible (resbalín / muro)'],
    favorece: ['Destreza', 'Equilibrio', 'Coordinación', 'Motricidad gruesa'],
    materiales: 'Terciado y pino, aceites naturales y tinte verde. Soporta hasta 40 kg',
    medidas: '100 cm de largo × 38 cm de ancho',
    imagenes: ['/img/productos/rampla/1.jpg', '/img/productos/rampla/2.jpg'],
    destacado: false, stock: true,
  },
  {
    slug: 'delfin-pez', nombre: 'Delfín Pez', precio: 0, consultar: true,
    edad: 'Desde 10 meses',
    descripcion: 'Juego de equilibrio en forma de delfín: una base curva y piezas redondas para apilar y balancear sin que se caigan. Un clásico de motricidad y paciencia.',
    incluye: ['Base en forma de delfín', 'Piezas redondas de madera para equilibrar'],
    favorece: ['Inicio del lenguaje e imitación', 'Motricidad fina', 'Imaginación', 'Coordinación', 'Equilibrio'],
    materiales: 'Pino, terminaciones con aceites naturales',
    imagenes: ['/img/productos/delfin-pez/1.jpg', '/img/productos/delfin-pez/2.jpg', '/img/productos/delfin-pez/3.jpg', '/img/productos/delfin-pez/4.jpg'],
    destacado: false, stock: true,
  },
  {
    slug: 'herramientas', nombre: 'Herramientas', precio: 0, consultar: true,
    edad: 'Desde 12 meses',
    descripcion: 'Set de herramientas de madera con su propia caja para jugar a construir y reparar. Ideal para el juego simbólico y la imitación de los grandes.',
    incluye: ['6 herramientas de madera', 'Caja de herramientas'],
    favorece: ['Motricidad fina y gruesa', 'Coordinación', 'Imitación y lenguaje', 'Juego simbólico y uso funcional de objetos'],
    materiales: 'Terciado, terminaciones con aceites naturales',
    imagenes: ['/img/productos/herramientas/1.jpg', '/img/productos/herramientas/2.jpg'],
    destacado: false, stock: true,
  },
  {
    slug: 'zapatito', nombre: 'Zapatito', precio: 0, consultar: true,
    edad: 'Desde 3 años',
    descripcion: 'Juego en forma de zapato para aprender a enhebrar y amarrar el cordón. Una entretenida manera de practicar la motricidad fina antes de los cordones de verdad.',
    incluye: ['Zapato de madera con perforaciones', 'Cordón'],
    favorece: ['Motricidad fina', 'Coordinación', 'Concentración'],
    materiales: 'Pino, terminaciones con aceites naturales',
    imagenes: ['/img/productos/zapatito/1.jpg'],
    destacado: false, stock: true,
  },
  {
    slug: 'ovejita-del-sur', nombre: 'Ovejita del Sur', precio: 0, consultar: true,
    edad: 'Desde 2 años',
    descripcion: 'Juego en forma de oveja para coser con lana usando una aguja de madera. Inspirado en el sur de Chile, invita a crear y a concentrarse.',
    incluye: ['Oveja de madera', 'Aguja de madera', 'Lana'],
    favorece: ['Motricidad fina', 'Coordinación', 'Concentración'],
    materiales: 'Pino, terminaciones con aceites naturales',
    imagenes: ['/img/productos/ovejita-del-sur/1.jpg', '/img/productos/ovejita-del-sur/2.jpg', '/img/productos/ovejita-del-sur/3.jpg'],
    destacado: false, stock: true,
  },
];

export function getProduct(slug) {
  return products.find(p => p.slug === slug);
}
